---
-
        vertex: res/Shaders/vertex.glsl
        fragment: res/Shaders/fragmentA.glsl
        name : ShaderA
-
        vertex: res/Shaders/vertex.glsl
        fragment: res/Shaders/fragmentB.glsl
        name : ShaderB
...